// Generated by https://quicktype.io

export interface Character {
  id: number;
  name: string;
  clas: string;
  weapon: string;
  age: number;
  race: string;
  birthday: string;
  height: string;
  weight: string;
  bloodType: string;
  sentence: string;
  description: string;
  nameHabilitySpecial: string;
  descriptionHabilitySpecial: string;
  background: string;
  speed: string;
  attackRange: string;
  difficulty: string;
  type: string;
  color: string;
  icon: CharacterIcon[];
  portrait: CharacterPortrait[];
  classTree: ClassTree[];
}

export interface ClassTree {
  id: number;
  name: string;
  nameClass: string;
  weapon: string;
  age: number;
  race: string;
  height: string;
  weight: string;
  espCollection: string;
  speed: string;
  attackRange: string;
  difficulty: string;
  type: string;
  background: string;
  idCharacter: number;
  icon: ClassTreeIcon[];
  portrait: ClassTreePortrait[];
}

export interface ClassTreeIcon {
  idFirstClass: number;
  icon: string;
}

export interface ClassTreePortrait {
  idFirstClass: number;
  portrait: string;
}

export interface CharacterIcon {
  idCharacter: number;
  icon: string;
}

export interface CharacterPortrait {
  idCharacter: number;
  portrait: string;
}
